model:
  base_learning_rate: 4.5e-6
  target: models.taming.models.vqgan.VQNoDiscModel
  params:
    # ckpt_path: last.ckpt
    monitor: 'val/total_loss_epoch'
    embed_dim: 4
    n_embed: 16384
    ddconfig:
      double_z: False
      z_channels: 4
      resolution: 512
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult:
      - 2
      - 2
      - 4
      - 4
      num_res_blocks: 1
      attn_resolutions: [64]
      dropout: 0.0

    lossconfig:
      target: models.taming.modules.losses.vqperceptual.VQLPIPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 1
        disc_start: 1000000
        disc_weight: 0.0
        codebook_weight: 1.0

data:
  target: data.MRIDataModule.MRIDataModule
  params:
    dataset_path: '../DB_IA-Gen-Med-Im_6578_predict_survie'
    manifest_filename: 'MRI_dataset_autoencoder.csv'
    task: 'autoencoder'
    seed: 23
    normalization: 'max'
    num_workers: 32
    batch_size: 5
    #crop_size: 480
    #resize_size: 256
    tanh_range: True
    data_augmentation: True
    train_val_test_shuffle: [True, False, False]
    train_val_test_split: [0.8, 0.1, 0.1]

lightning:
  trainer:
    benchmark: True
    accelerator: auto  # cpu, gpu, tpu, hpu or auto
    devices: auto
    strategy: auto
    #strategy: ddp_find_unused_parameters_true for multi gpus
    #accumulate_grad_batches: 2